version: '3'

services:

  mysql:
    image: mysql:5.7.21
    volumes:
      - ortopedica-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - ortopedica
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fe-conta

  web:
    build: .
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./src:/app
    links:
      - mysql:mysql
    ports:
      - "9000:8000"
    networks:
      - ortopedica
    environment:
       DATABASE_URL: mysql://root:password@mysql:3306/fe-conta
    depends_on:
      - mysql

volumes:
  ortopedica-mysql:
  ortopedica-python:

networks:
  ortopedica:
