version: '3'

services:

  mysql-conta:
    image: mysql:5.7.21
    volumes:
      - mysql-conta:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fe-conta

  conta:
    build: .
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./src:/app
    ports:
      - "9000:8000"
    environment:
       DATABASE_URL: mysql://root:password@mysql-conta:3306/fe-conta
    depends_on:
      - mysql-conta

volumes:
  mysql-conta:

networks:
  default:
    external:
      name: fe
