apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: fe-conta-server
  name: fe-conta-server
spec:
  template:
    metadata:
      labels:
        app: fe-conta-server
    spec:
      containers:
        - name: fe-conta-server
          image: fernandoe/fe-conta-server:bootstrap
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
