apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.21
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            value: conta
          - name: MYSQL_ROOT_PASSWORD
            value: password
