apiVersion: v1
kind: Service
metadata:
  labels:
    app: fe-conta-server
  name: fe-conta-server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: fe-conta-server
  type: LoadBalancer
